### ISSUE TITLE
Pip install broken

### ISSUE THREAD

**Issue by Glench** [philipbjorge/EditREPL#5]
```
glen@puku$ pip install editrepl
  ...
  File "<string>", line 14, in <module>

  File "/Users/glen/.virtualenvs/33b7ea7587872107/build/editrepl/setup.py", line 13, in <module>

    long_description=open('README_pypi.rst').read()

IOError: [Errno 2] No such file or directory: 'README_pypi.rst'
```

Happens not in a virtual environment as well.

**Comment by philipbjorge** [comment]
Hey @Glench ,
Thanks for this report. I forgot to include the README.rst with the distributed package (which explains why I wasn't seeing a pretty README on the pypi project page in April).

I've pushed an updated version and everything installed fine in my clean virtual machine.
Could you respond with your results?

**Comment by Glench** [comment]
It works! Thank you for your responsiveness! Love this library.
